version: '3.9'
services:
  postgresql:
    image: postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - ./docker_volumes:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef

